### ISSUE TITLE
Simplify default path in appveyor

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#22]
Hi,

I am assigning this issue to myself :) . In the *appveyor.yml* file I have to simplify the %path% setting.

As Ivan suggested, there can be this simple structure below. I have to play to determine which path-segments are necessary for our autocmake appveyor-CI tests.

```
version: 1.0.{build}
init:
- ps: >-
    cd C:\projects\autocmake
environment:
  line_1: First;Line
  line_2: Second;Line
  line_x: X;Line
  path: 'C:\Program Files (x86)\Git\cmd;%line_1%;%line_2%;%line_x%'
  default: '%path%'
build_script:
- echo %path%
- set path=%path%;next++
- echo %path%
- echo %default%
```
